name: SwornShop
main: qs.swornshop.Main
description: Shop plugin
version: 1.0
commands:
    shop:
        description: manage shops
        usage: |
          /shop <action> <arguments...>
          §6Help: §f/shop help
    s:
        description: an alias for shop
        usage: |
          /s <action> <arguments...>
          §6Help: §f/shop help
permissions:
    swornshop.*:
        description: All SwornShop permissions
        default: op
        children:
            shops.admin: true
            shops.trader: true
    swornshop.trader:
        description: Allows you to buy and sell from shops
        default: true
        children:
            swornshop.buy: true
            swornshop.sell: true
    swornshop.admin:
        description: Allows you to create and remove shops
        default: op
    swornshop.self:
        description: Allows you to manipulate your own shops as if they were others
        default: op