name: Shops
main: qs.shops.Main
description: A plugin that ads shops to minecraft using vaults economy feature
version: 2.0
commands:
    shop:
        description: manage shops
        usage: |
          /shop <action> <arguments...>
          ยง6Help: ยงf/shop help
        aliases: s
permissions:
    shops.*:
        description: All Shops permissions
        default: op
        children:
            shops.admin: true
            shops.trader: true
    shops.trader:
        description: Allows you to buy and sell from shops
        default: true
        children:
            shops.buy: true
            shops.sell: true
    shops.admin:
        description: Allows you to create and remove shops
        default: op
    shops.self:
        description: Allows you to manipulate your own shops as if they were others
        default: op