name: SwornShop
main: qs.swornshop.Main
description: Shop plugin
version: 1.0
commands:
    shop:
        description: manage shops
        usage: |
          /shop <action> <arguments...>
          ยง6Help: ยงf/shop help
permissions:
  shops.*:
    description: All SwornShop permissions
    default: op
    children:
      shops.admin: true
  shops.admin:
    description: allows the user to create and remove shops
    default: op
    