#  ____                ____   _
# | __ )   __ _ __  __/ ___| | |__    ___   _ __   ___
# |  _ \  / _` |\ \/ /\___ \ | '_ \  / _ \ | '_ \ / __|
# | |_) || (_| | >  <  ___) || | | || (_) || |_) |\__ \
# |____/  \__,_|/_/\_\|____/ |_| |_| \___/ | .__/ |___/
#                                          |_|
# Backups: 15                                                   # Number of backups to keep. Set this to -1 to never delete old backups
# LogNotes: false                                                # Show all notifications in log
#
Backups: 15
LogNotes: false