#################################################
#      __   ____ _____ ___ ___ __  __ ____      #
#     / _ \|  _ \_   _|_ _/ _ \| \ | / ___|     #
#    | | | | |_) || |  | | | | |  \| \___ \     #
#    | |_| |  __/ | |  | | |_| | |\  |___) |    #
#     \___/|_|    |_| |___\___/|_| \_|____/     #
#################################################

# Number of backups to keep. Set this to -1 to never delete old backups
# Please delete all your backups if you chose to modify this after creating many backups
Backups: 15

# Show all notifications in log
LogNotes: false

# How much 1 XP level costs.
XPConvert: 4.00

# Stupid deaths can be taxed by percentage and deposited into an account. 
# Uncomment this structure to enable this feature. The default UUID
# below is a dummy account. If used, funds will not be deposited into any account.
#
# DeathTax:
#      GoesTo:     "326a36ea-b465-3192-a4f7-c313f347edc9"
#      Percentage: 0.04
#      Minimum:    100.00